# fast_dev_run: false # Enable this for debug purposes
devices: -1
accelerator: gpu
precision: 32
max_epochs: 1
accumulate_grad_batches: 1
gradient_clip_val: 1.0
gradient_clip_algorithm: norm
val_check_interval: 1.0

# profiler: simple

